In [ ]:
# Install SQL package for R
install.packages("sqldf")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’

In [ ]:
# Load sqldf library
library(sqldf)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite

In [ ]:
#High Value Customers    customers <- read.csv("/content/customers.csv")
colnames(customers) # Added to inspect column names

sqldf("
SELECT customer_id,
       loyalty_score
FROM customers
WHERE loyalty_score > 80
ORDER BY loyalty_score DESC
")

[1] "customer_id"          "age"                  "home_zone"
[4] "customer_type"        "signup_date"          "loyalty_score"
[7] "app_engagement_score" "preferred_channel"    "account_status"

   customer_id loyalty_score
1  C0125       99.0
2  C0145       99.0
3  C0146       99.0
4  C0299       99.0
5  C0321       99.0
6  C0333       99.0
7  C0563       99.0
8  C0629       99.0
9  C0593       98.8
10 C0179       97.9
11 C0594       97.4
12 C0108       96.0
13 C0433       95.3
14 C0278       95.2
15 C0213       94.2
16 C0014       94.1
17 C0174       93.5
18 C0345       93.5
19 C0138       93.2
20 C0399       93.0
21 C0585       91.1
22 C0121       90.9
23 C0500       90.6
24 C0550       89.4
25 C0516       88.9
26 C0150       88.8
27 C0354       87.8
28 C0286       87.7
29 C0586       87.4
30 C0010       87.2
⋮  ⋮           ⋮
34 C0120       86.8
35 C0175       86.4
36 C0527       86.2
37 C0281       85.4
38 C0060       85.2
39 C0032       85.0
40 C0401       85.0
41 C0046       84.8
42 C0008       84.6
43 C0538       84.5
44 C0583       84.2
45 C0391       84.1
46 C0193       84.0
47 C0176       83.8
48 C0242       83.8
49 C0041       83.5
50 C0134       83.3
51 C0409       82.8
52 C0171       82.4
53 C0465       82.4
54 C0579       82.4
55 C0612       82.3
56 C0045       82.0
57 C0475       81.9
58 C0080       81.6
59 C0450       81.6
60 C0599       81.4
61 C0047       81.3
62 C0444       80.5
63 C0055       80.3

In [ ]:
#View Customer Dataset # Display first 5 customer records
head(customers)

  customer_id age home_zone customer_type signup_date         loyalty_score
1 C0001       26  North     SME           2024-11-27 04:25:00 44.9
2 C0002       61  AIRPORT   Consumer      2025-10-28 01:04:00 55.4
3 C0003       66  East      Consumer      2025-07-02 03:23:00 75.9
4 C0004       75  CENTRAL   Consumer      2025-08-19 01:58:00 32.5
5 C0005       26  Riverside Consumer      2025-06-03 06:02:00 55.9
6 C0006       41  WEST      Consumer      2024-03-29 13:26:00 39.9
  app_engagement_score preferred_channel account_status
1  69.2                App               Active
2  66.6                App               Active
3  33.8                                  Active
4  33.0                App               Active
5 100.0                Web               Active
6  43.3                Web               Active

In [ ]:
# Failed and delayed delivery analysis
deliveries <- read.csv("/content/deliveries.csv")


sqldf(
"SELECT delivery_id,
       delivery_status,
       route_distance_km
FROM deliveries
WHERE delivery_status = 'Failed'
   OR delivery_status = 'Delayed'
")

    delivery_id delivery_status route_distance_km
1   DL00001     Failed          17.26
2   DL00004     Delayed         16.42
3   DL00006     Delayed         13.84
4   DL00007     Delayed         32.72
5   DL00010     Failed           9.85
6   DL00012     Failed          16.96
7   DL00017     Delayed         20.79
8   DL00022     Failed          15.81
9   DL00026     Failed          14.27
10  DL00028     Delayed         15.53
11  DL00033     Failed          11.72
12  DL00034     Delayed         14.68
13  DL00038     Failed           8.82
14  DL00039     Failed          17.13
15  DL00040     Failed           9.53
16  DL00041     Failed          15.88
17  DL00048     Delayed          7.37
18  DL00052     Delayed         26.38
19  DL00054     Delayed         29.80
20  DL00055     Delayed         35.07
21  DL00057     Failed          10.91
22  DL00059     Delayed         36.28
23  DL00060     Delayed         13.92
24  DL00064     Delayed         10.36
25  DL00068     Failed          19.75
26  DL00069     Failed          16.76
27  DL00071     Delayed         20.37
28  DL00072     Delayed         28.51
29  DL00074     Failed          17.61
30  DL00077     Delayed         32.97
⋮   ⋮           ⋮               ⋮
305 DL00859     Delayed         24.20
306 DL00862     Failed           8.40
307 DL00868     Failed           6.57
308 DL00872     Delayed         15.53
309 DL00874     Delayed         10.15
310 DL00879     Delayed          9.42
311 DL00881     Delayed         12.77
312 DL00883     Delayed         11.42
313 DL00886     Delayed          1.20
314 DL00888     Failed          11.78
315 DL00889     Failed           7.09
316 DL00890     Delayed          9.61
317 DL00893     Delayed         25.18
318 DL00894     Delayed         25.57
319 DL00898     Delayed         10.44
320 DL00905     Delayed         30.71
321 DL00906     Failed          18.60
322 DL00909     Delayed         10.35
323 DL00910     Delayed         26.61
324 DL00912     Delayed         21.47
325 DL00920     Failed           5.08
326 DL00921     Failed           6.36
327 DL00922     Delayed         12.65
328 DL00925     Delayed         13.04
329 DL00928     Failed          12.72
330 DL00931     Failed          16.08
331 DL00935     Failed          32.42
332 DL00938     Failed          36.94
333 DL00940     Delayed         16.19
334 DL00942     Failed          12.99

In [ ]:
# Upload
customers <- read.csv("customers.csv")
orders <- read.csv("orders.csv")
deliveries <- read.csv("deliveries.csv")
complaints <- read.csv("complaints.csv")

In [ ]:
# Display first 6 customer records
head(customers)

  customer_id age home_zone customer_type signup_date         loyalty_score
1 C0001       26  North     SME           2024-11-27 04:25:00 44.9
2 C0002       61  AIRPORT   Consumer      2025-10-28 01:04:00 55.4
3 C0003       66  East      Consumer      2025-07-02 03:23:00 75.9
4 C0004       75  CENTRAL   Consumer      2025-08-19 01:58:00 32.5
5 C0005       26  Riverside Consumer      2025-06-03 06:02:00 55.9
6 C0006       41  WEST      Consumer      2024-03-29 13:26:00 39.9
  app_engagement_score preferred_channel account_status
1  69.2                App               Active
2  66.6                App               Active
3  33.8                                  Active
4  33.0                App               Active
5 100.0                Web               Active
6  43.3                Web               Active

In [ ]:
# Select customer records
sqldf("
SELECT *
FROM customers
LIMIT 5
")

  customer_id age home_zone customer_type signup_date         loyalty_score
1 C0001       26  North     SME           2024-11-27 04:25:00 44.9
2 C0002       61  AIRPORT   Consumer      2025-10-28 01:04:00 55.4
3 C0003       66  East      Consumer      2025-07-02 03:23:00 75.9
4 C0004       75  CENTRAL   Consumer      2025-08-19 01:58:00 32.5
5 C0005       26  Riverside Consumer      2025-06-03 06:02:00 55.9
  app_engagement_score preferred_channel account_status
1  69.2                App               Active
2  66.6                App               Active
3  33.8                                  Active
4  33.0                App               Active
5 100.0                Web               Active

In [ ]:
# Find customers from London
# The column names for 'customers' are: "customer_id", "age", "home_zone", "customer_type", "signup_date", "loyalty_score", "app_engagement_score", "preferred_channel", "account_status"
# It appears 'home_zone' is the appropriate column for location.
sqldf("
SELECT *
FROM customers
WHERE home_zone = 'London'
")

     customer_id age home_zone customer_type signup_date loyalty_score
     app_engagement_score preferred_channel account_status

In [ ]:
# Count customers by home_zone
# The previous error indicated 'no such column: city'.
# Based on earlier analysis, 'home_zone' is the correct column name for location.
sqldf("
SELECT home_zone,
       COUNT(*) AS total_customers
FROM customers
GROUP BY home_zone
")

   home_zone total_customers
1  AIRPORT   34
2  Airport   35
3  CENTRAL   44
4  Central   33
5  Ctr       33
6  EAST      41
7  East      48
8  NORTH     33
9  North     39
10 RiverSide 49
11 Riverside 42
12 SOUTH     50
13 South     42
14 WEST      45
15 West      43
16 north     39

In [ ]:
# Join customers and orders
# The previous check confirmed that there is no 'order_status' column in the orders data frame.
# The available columns are: "order_id", "customer_id", "service_type", "order_created_at", "promised_window_hours", "pickup_zone", "dropoff_zone", "priority_level", "order_value", "booking_channel", "special_handling_flag"
# We will use 'service_type' as the appropriate column for order status.
sqldf("
SELECT customers.customer_id,
       orders.order_id,
       orders.service_type
FROM customers
JOIN orders
ON customers.customer_id = orders.customer_id
LIMIT 5
")

  customer_id order_id service_type
1 C0001       O00007   Business
2 C0001       O00666   Parcel
3 C0001       O00721   Retail
4 C0002       O00659   Retail
5 C0003       O00261   Passenger

In [ ]:
# Find deliveries delayed more than 30 minutes
# The error 'no such column: delay_minutes' means this column does not exist in the deliveries data frame.
# Let's inspect the column names of the 'deliveries' data frame to find the correct column.
print(colnames(deliveries))

# Original query (commented out until the correct column name is identified)
# sqldf("
# SELECT *
# FROM deliveries
# WHERE delay_minutes > 30
# ")

 [1] "delivery_id"                   "order_id"
 [3] "driver_id"                     "vehicle_id"
 [5] "hub_id"                        "dispatch_time"
 [7] "delivery_completed_at"         "delivery_status"
 [9] "route_distance_km"             "manual_route_override_count"
[11] "proof_of_completion_missing"   "customer_rating_post_delivery"
[13] "fuel_or_charge_cost"

In [ ]:
# Count complaints by issue type
# The previous error indicated 'no such column: issue_type'.
# Based on the column names, 'complaint_type' is the appropriate column to use.
sqldf("
SELECT complaint_type,
       COUNT(*) AS total_complaints
FROM complaints
GROUP BY complaint_type
")

  complaint_type    total_complaints
1 AppIssue           53
2 Billing            16
3 Damage             15
4 Delay             101
5 DriverBehaviour    51
6 MissedPickup       64
7 SupportExperience  20

In [ ]:
# Retrieve only necessary columns
# The error 'no such column: city' means this column does not exist in the customers data frame.
# As previously identified, 'home_zone' is the correct column for location.
sqldf("
SELECT customer_id,
       home_zone
FROM customers
WHERE home_zone = 'Manchester'
")

     customer_id home_zone

In [ ]:
#Driver performance analysis
sqldf(
"SELECT driver_id,
       AVG(customer_rating_post_delivery) AS average_rating,
       COUNT(delivery_id) AS total_deliveries
FROM deliveries
GROUP BY driver_id
ORDER BY average_rating ASC
")

    driver_id average_rating total_deliveries
1   D063      2.373333        3
2   D111      2.637500        4
3   D076      2.672500        4
4   D141      2.934444        9
5   D165      2.976667        6
6   D147      3.100000        2
7   D021      3.105000        2
8   D091      3.130000        6
9   D053      3.137143        7
10  D137      3.145000        4
11  D051      3.180000        2
12  D002      3.210000        7
13  D095      3.264000        5
14  D103      3.280000        4
15  D016      3.331667        7
16  D162      3.335000        5
17  D011      3.338333        6
18  D100      3.348750        8
19  D078      3.368333        6
20  D092      3.376000        5
21  D140      3.400000        3
22  D124      3.412500        4
23  D112      3.415000        2
24  D085      3.417500        4
25  D133      3.423333       12
26  D024      3.443750        8
27  D052      3.447143        8
28  D159      3.453333        3
29  D170      3.507500        4
30  D004      3.510000        9
⋮   ⋮         ⋮              ⋮
141 D142      4.253750        9
142 D115      4.273333        3
143 D007      4.285000        2
144 D110      4.286667        7
145 D039      4.287778        9
146 D030      4.312857        7
147 D152      4.323333        3
148 D036      4.337778        9
149 D164      4.341250        8
150 D125      4.345000        8
151 D167      4.347500        4
152 D163      4.350000        6
153 D012      4.380000        2
154 D044      4.380000        3
155 D108      4.411818       11
156 D014      4.427500        4
157 D126      4.428000        5
158 D138      4.437500        4
159 D003      4.445000        4
160 D013      4.517500        4
161 D015      4.521667        6
162 D066      4.560000        1
163 D081      4.600000        2
164 D061      4.610000        4
165 D025      4.653333        3
166 D118      4.662500        4
167 D122      4.716667        3
168 D065      4.935000        2
169 D035      5.000000        2
170 D059      5.000000        1

In [ ]:
# Route and operational zone analysis
sqldf(
"SELECT hub_id,
       COUNT(*) AS delayed_deliveries_count
FROM deliveries
WHERE delivery_status = 'Delayed'
GROUP BY hub_id
ORDER BY delayed_deliveries_count DESC
")

  hub_id delayed_deliveries_count
1 H04    28
2 H06    27
3 H02    26
4 H01    26
5 H07    25
6 H05    25
7 H03    23
8 H08    22